### ISSUE TITLE
Unable to deploy the 3.1.2 version

### ISSUE THREAD

**Issue by cornelcroi** [aws-solutions/live-stream-on-aws#37]
**Describe the bug**
The 3.1.2 seems to have a bug.
I deployed the 3.1.1 solution several times, but for about one week I'm unable to deploy it and it seems to be the 3.1.2 version right now, released a few days ago.

**To Reproduce**
Deploy the template in `us-east-1` or `eu-west-1`

**Expected behavior**

**Please complete the following information about the solution:**

- [x] Version: v3.1.2
- [x] Region: us-east-1, us-west-1
- [x] Was the solution modified from the version published on this repository? No
- [ ] 
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x ] Were there any errors in the CloudWatch Logs? No
I have errors on CloudFormation console

`CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [08c5a1d5-5a28-4736-9e38-b2c35ab3a13c]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.`

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
The deployment is stuck for about one hour and then the error above is displayed then a rollback is triggered.

**Comment by eggoynes** [comment]
Hi @cornelcroi

We are taking a look. Thank you for brining this up.
