### ISSUE TITLE
[Don't Create Medichanel from Cloudformation teamplate]

### ISSUE THREAD

**Issue by NguyenDOanNhan** [aws-solutions/live-stream-on-aws#49]
** Description of the error **
The error could not create a mediachannel with cloudformation tamplate.

** To reproduce **
Execute teamplate run
Enter name stack
Create stack
** Expected behavior **
Create a solution

** Please complete the following information about the solution: **
- [] Version: Version 4.0.1
                          Last updated: 08/2022
                         Author: AWS
- [] Region: US East (N. Virginia)
us-east-1

** Screenshots **
If possible, add a screenshot to help explain your issue (please do NOT include sensitive information).

** Additional context **
After I run the template there was an error lambda couldn't read the SSM paramter store, I fixed this by fixing the teamplate.
- "ssm:GetParameters"
- "ssm:GetParameter"
After running the template again, I have to wait more than 1 hour, but the mediachannel is still not created.

**Comment by NguyenDOanNhan** [comment]
![error_dont_create_mediachanel_more_then_one_hour](https://user-images.githubusercontent.com/43739331/190109266-82a9333b-306f-401d-b00a-a251d70a55a8.png)

**Comment by cassneal** [comment]
Thank you for opening this issue. We have added this to our backlog to look into.

**Comment by cassneal** [comment]
Hi @NguyenDOanNhan,

Can you answer a few questions for us? 
1) What values are you using for the parameters in the cloudformation stack? 
2) What input type? 
3) Does this repro consistently for you every single time? Did you ever successfully create a mediachannel? 
4) Any other details to help us reproduce. 

Thank you!
